<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AM | Assets manager</title>
        <?php echo $this->headTitle()."\n";?>

        <!--CSS-->
        <link rel="stylesheet" type="text/css" href="/css/style.css">

        <!--FONT-->
        
        <!--JAVASCRIPT-->
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    </head>
    <body>

        <?php echo $this->layout()->content;?>
    </body>
</html>