<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AM | Assets manager</title>
        <?php echo $this->headTitle()."\n";?>

        <!--CSS-->
        <link rel="stylesheet" type="text/css" href="/css/style.css">

        <!--FONT-->
        
        <!--JAVASCRIPT-->
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    </head>
    <body>
        
        <div class="header">
            <div class="container">
                <div class="row">
                    <div class="span4">
                        <a href="/"><img src="/img/logo.png" alt=""></a>
                    </div>
                    <div class="span4 offset4">
                        <div class="profile-box">
                            <span>Bienvenido terricola</span>    
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- <div class="heading">
            <div class="container">
                <h1>Asset Management</h1>
            </div>
        </div>

        <div class="page">
            <div class="container">
                <div class="row-fluid">
                    <div class="span4 offset4">
                        <div class="panel panel-outer">
                            <div class="panel-heading">
                                <span>Iniciar Sesión</span>
                            </div>
                            <div class="panel-body">
                                <form method="post" action="/signup" class="clearfix unstyled">
                                    <input type="text" class="input-block-level" placeholder="Nombre de usuario" name="Nombre de usuario">
                                    <input type="password"class="input-block-level" placeholder="Password" name="password">
                                    <input type="submit" class="btn btn-success pull-right" value="Login">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> -->

        <div>
            <?php echo $this->layout()->content;?>
        </div>


        <div class="footer">
            Accenture, 2013.
        </div>

    </body>
</html>